# Problem-Solving with NumPy


#### 1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’



In [15]:
import numpy as np

def foo_1(arr, target):
 
    sorted_arr= np.argsort(np.abs(arr - target))
    
    if target not in arr:
        return "no item found"

    return sorted_arr                                    

In [16]:
arr = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])
target = 7
result = foo_1(arr, target)
print(result)  

[2 3 4 5 6 8 1 7 9 0]


In [17]:
target = 11
result = foo_1(arr, target)
print(result)                                         

no item found


#### 2. Write a user defined function foo_2 that takes a 1 or 2 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis.

In [3]:
import numpy as np

def foo_2(arr, axis=0):
 
  if arr.ndim not in [2, 3]:
    raise ValueError("Input array must be 2 or 3 dimensional.")

  
  return np.count_nonzero(arr, axis=axis)

arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])
s = foo_2(arr, axis = 0)
print(s)

[2 2 2 1]


In [4]:
s = foo_2(arr, axis = 1)
print(s)

[4 1 2]


In [5]:
def foo_3(arr, axis=0):
 
  if arr.ndim not in [2, 3]:
    raise ValueError("Input array must be 2 or 3 dimensional.")

  
  return np.count_nonzero(arr, axis=axis)


In [6]:
arr = np.array([[[1, 2, 3, 4],[0, 5, 0, 0],[2, 0, 1, 0]],
                [[2, 0, 1, 0],[0, 5, 0, 0],[1, 2, 3, 4]]])
s = foo_3(arr,axis = 0)
print(s)

[[2 1 2 1]
 [0 2 0 0]
 [2 1 2 1]]


In [7]:
s = foo_3(arr,axis = 1)
print(s)

[[2 2 2 1]
 [2 2 2 1]]


In [8]:
s = foo_3(arr,axis = 2)
print(s)

[[4 1 2]
 [2 1 4]]


#### 3.1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.

In [19]:
import numpy as np

data = np.array([[85,89,88],
                [78,89,94],
                [91,87,90],
                [87,95,84]])

students_above_90 = np.any(data > 90, axis=1)

data[students_above_90]


array([[78, 89, 94],
       [91, 87, 90],
       [87, 95, 84]])

#### 3.2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.

In [23]:
import numpy as np

data = np.array([[120, 150, 130, 110],
                [200, 180, 220, 250],
                [90, 100, 95, 110],
                [300, 280, 320, 340]])

stats = np.vstack([np.mean(data, axis=1), np.median(data, axis=1), np.std(data, axis=1), np.argmax(data, axis=1)])

labels = ["Mean", "Median", "Std. Dev.", "Highest Month"]

for i, product in enumerate(data):
    print(f"Product {i+1}:")
    for stat, label in zip(stats[:, i], labels):
        print(f"\t{label}: {stat:.2f}")

Product 1:
	Mean: 127.50
	Median: 125.00
	Std. Dev.: 14.79
	Highest Month: 1.00
Product 2:
	Mean: 212.50
	Median: 210.00
	Std. Dev.: 25.86
	Highest Month: 3.00
Product 3:
	Mean: 98.75
	Median: 97.50
	Std. Dev.: 7.40
	Highest Month: 3.00
Product 4:
	Mean: 310.00
	Median: 310.00
	Std. Dev.: 22.36
	Highest Month: 3.00


#### 3.3 Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.


In [22]:
import numpy as np
from collections import Counter

data = np.random.randint(1, 101, size=1000)

counts = Counter(data)

top_10 = counts.most_common(10)

print("Top 10 most frequent values in the array:")
for value, count in top_10:
    print(f"\t- {value}: {count} occurrences")

Top 10 most frequent values in the array:
	- 73: 20 occurrences
	- 70: 17 occurrences
	- 32: 16 occurrences
	- 49: 15 occurrences
	- 99: 15 occurrences
	- 94: 15 occurrences
	- 78: 15 occurrences
	- 64: 15 occurrences
	- 95: 14 occurrences
	- 5: 14 occurrences


#