In [1]:
import numpy as np

In [7]:
arr = np.array([[1,2,3,4],[4,5,6,7]])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.ndim

2

In [10]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [12]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [13]:
k = [1,2,3,4,5,6,7,8,9,10]
k

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
k[1:6]

[2, 3, 4, 5, 6]

In [19]:
k[2:10:3]

[3, 6, 9]